// Transform-related block definitions
export const transformBlocks = {
  set_position: {
    type: "set_position",
    message0: "set %1 position to %2",
    args0: [
      { type: "input_value", name: "NODE" },
      { type: "input_value", name: "POSITION" },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: "Set node position",
    helpUrl: "",
  },
  set_rotation: {
    type: "set_rotation",
    message0: "set %1 rotation to %2",
    args0: [
      { type: "input_value", name: "NODE" },
      { type: "input_value", name: "ROTATION" },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: "Set node rotation",
    helpUrl: "",
  },
  add_position: {
    type: "add_position",
    message0: "add to %1 position %2",
    args0: [
      { type: "input_value", name: "NODE" },
      { type: "input_value", name: "POSITION" },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: "Add position to current position",
    helpUrl: "",
  },
  add_rotation: {
    type: "add_rotation",
    message0: "add to %1 rotation %2",
    args0: [
      { type: "input_value", name: "NODE" },
      { type: "input_value", name: "ROTATION" },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: "Add rotation to current rotation",
    helpUrl: "",
  },
  set_scale: {
    type: "set_scale",
    message0: "set %1 scale to %2",
    args0: [
      { type: "input_value", name: "NODE" },
      { type: "input_value", name: "SCALE" },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: "Set node scale",
    helpUrl: "",
  },
  get_scale: {
    type: "get_scale",
    message0: "%1 scale",
    args0: [{ type: "input_value", name: "NODE" }],
    output: "Vector3",
    colour: 160,
    tooltip: "Get node scale",
    helpUrl: "",
  },
  set_world_position: {
    type: "set_world_position",
    message0: "set %1 world position to %2",
    args0: [
      { type: "input_value", name: "NODE" },
      { type: "input_value", name: "POSITION" },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: "Set node world position",
    helpUrl: "",
  },
  get_world_position: {
    type: "get_world_position",
    message0: "%1 world position",
    args0: [{ type: "input_value", name: "NODE" }],
    output: "Vector3",
    colour: 160,
    tooltip: "Get node world position",
    helpUrl: "",
  },
};
