// Blockly toolbox configuration
export const toolboxConfig = {
  kind: "categoryToolbox",
  contents: [
    {
      kind: "category",
      name: "Variables",
      colour: "#A65C81",
      custom: "VARIABLE",
    },
    {
      kind: "category",
      name: "GameMode",
      colour: "#FF6B6B",
      contents: [
        { kind: "block", type: "gamemode_start" },
        { kind: "block", type: "gamemode_update" },
        { kind: "block", type: "declare_variable" },
        { kind: "block", type: "declare_local_variable" },
      ],
    },
    {
      kind: "category",
      name: "Space & Nodes",
      colour: "#4ECDC4",
      contents: [
        { kind: "block", type: "get_space" },
        { kind: "block", type: "create_node" },
        { kind: "block", type: "add_node_to_space" },
        { kind: "block", type: "get_nodes" },
        { kind: "block", type: "get_node_name" },
        { kind: "block", type: "destroy_node" },
      ],
    },
    {
      kind: "category",
      name: "Components",
      colour: "#45B7D1",
      contents: [
        { kind: "block", type: "add_gltf_component" },
        { kind: "block", type: "add_component" },
        { kind: "block", type: "add_component_by_name" },
      ],
    },
    {
      kind: "category",
      name: "Transform",
      colour: "#96CEB4",
      contents: [
        { kind: "block", type: "set_position" },
        { kind: "block", type: "set_rotation" },
        { kind: "block", type: "add_position" },
        { kind: "block", type: "add_rotation" },
        { kind: "block", type: "set_scale" },
        { kind: "block", type: "get_scale" },
        { kind: "block", type: "set_world_position" },
        { kind: "block", type: "get_world_position" },
      ],
    },
    {
      kind: "category",
      name: "Vectors & Math",
      colour: "#FFEAA7",
      contents: [
        { kind: "block", type: "vector3_create" },
        { kind: "block", type: "vector3_distance" },
        { kind: "block", type: "vector3_component" },
        { kind: "block", type: "multiply_number" },
        { kind: "block", type: "math_number" },
        { kind: "block", type: "number_literal" },
        { kind: "block", type: "math_arithmetic" },
      ],
    },
    {
      kind: "category",
      name: "Time & Camera",
      colour: "#DDA0DD",
      contents: [
        { kind: "block", type: "delta_time" },
        { kind: "block", type: "get_main_camera" },
        { kind: "block", type: "camera_position" },
      ],
    },
    {
      kind: "sep",
    },
    {
      kind: "category",
      name: "Logic",
      colour: "#5C81A6",
      contents: [
        { kind: "block", type: "controls_if" },
        { kind: "block", type: "if_statement_comparison" },
        { kind: "block", type: "logic_compare" },
        { kind: "block", type: "logic_operation" },
        { kind: "block", type: "logic_negate" },
        { kind: "block", type: "logic_boolean" },
        { kind: "block", type: "boolean_literal" },
        { kind: "block", type: "logic_null" },
        { kind: "block", type: "logic_ternary" },
        { kind: "block", type: "return_statement" },
      ],
    },
    {
      kind: "category",
      name: "Loops",
      colour: "#5CA65C",
      contents: [
        { kind: "block", type: "controls_repeat_ext" },
        { kind: "block", type: "controls_repeat" },
        { kind: "block", type: "controls_whileUntil" },
        { kind: "block", type: "controls_for" },
        { kind: "block", type: "for_loop_array" },
        { kind: "block", type: "controls_forEach" },
        { kind: "block", type: "controls_flow_statements" },
      ],
    },
    {
      kind: "category",
      name: "Arrays",
      colour: "#8B5A99",
      contents: [
        { kind: "block", type: "array_index" },
        { kind: "block", type: "array_length" },
      ],
    },
    {
      kind: "category",
      name: "Text",
      colour: "#5CA68D",
      contents: [
        { kind: "block", type: "text" },
        { kind: "block", type: "text_join" },
        { kind: "block", type: "string_concat" },
        { kind: "block", type: "text_append" },
        { kind: "block", type: "text_length" },
        { kind: "block", type: "text_isEmpty" },
        { kind: "block", type: "text_indexOf" },
        { kind: "block", type: "text_charAt" },
        { kind: "block", type: "text_getSubstring" },
        { kind: "block", type: "text_changeCase" },
        { kind: "block", type: "text_trim" },
        { kind: "block", type: "text_print" },
        { kind: "block", type: "print_statement" },
        { kind: "block", type: "string_find" },
        { kind: "block", type: "string_format" },
      ],
    },
    {
      kind: "sep",
    },
    {
      kind: "category",
      name: "Variables",
      colour: "#A65C81",
      custom: "VARIABLE",
    },
    {
      kind: "category",
      name: "Functions",
      colour: "#9A5CA6",
      contents: [{ kind: "block", type: "anonymous_function" }],
      custom: "PROCEDURE",
    },
  ],
};
